#ifndef CHRONO_WEB_HTML_H
#define CHRONO_WEB_HTML_H

/* Static dashboard HTML/CSS/JS, served as-is by web_status.c's "GET /"
 * handler - extends dpdk-app-example/src/status_page_html.h's exact
 * visual language (CSS custom-property palette, pill/card/hero/meter/
 * tiles/tableview vocabulary, IBM Plex Sans/Mono via Google Fonts, one
 * polling IIFE) with a recording-control card, NVMe tiles, and an
 * interactive segments table. All dynamic content is client-side: this
 * page's own JS polls /status.json every second, and refreshes
 * /segments.json on load and after any start/stop/delete action.
 *
 * Deliberately pure ASCII (glyphs/punctuation as \uXXXX JS escapes or CSS
 * \XXXX escapes, not raw UTF-8 bytes) - the sibling project's own page
 * once rendered as mojibake in the browser from a raw multi-byte
 * character surviving into the C string literal; keeping this ASCII-only
 * means that class of bug can't recur here regardless of any future
 * header/pipeline change. */
static const char CHRONO_WEB_HTML[] =
	"<meta charset='utf-8'>\n"
	"<title>Chrontabulator</title>\n"
	"<link rel='preconnect' href='https://fonts.googleapis.com'>\n"
	"<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>\n"
	"<link href='https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap' rel='stylesheet'>\n"
	"<style>\n"
	"  :root {\n"
	"    color-scheme: light;\n"
	"    --bg:         #f6f8f7;\n"
	"    --surface:    #ffffff;\n"
	"    --surface-2:  #eef2f1;\n"
	"    --border:     rgba(10,20,18,0.10);\n"
	"    --text:       #0d1512;\n"
	"    --text-2:     #4c5754;\n"
	"    --text-mute:  #838d8a;\n"
	"    --accent:     #0e8f86;\n"
	"    --accent-soft: rgba(14,143,134,0.12);\n"
	"    --track:      #dfe6e4;\n"
	"\n"
	"    --good:     #0ca30c;\n"
	"    --critical: #d03b3b;\n"
	"\n"
	"    --font-ui:   'IBM Plex Sans', system-ui, -apple-system, 'Segoe UI', sans-serif;\n"
	"    --font-mono: 'IBM Plex Mono', ui-monospace, 'SFMono-Regular', Menlo, monospace;\n"
	"  }\n"
	"  @media (prefers-color-scheme: dark) {\n"
	"    :root:not([data-theme='light']) {\n"
	"      color-scheme: dark;\n"
	"      --bg:         #0a0f0e;\n"
	"      --surface:    #121917;\n"
	"      --surface-2:  #16201d;\n"
	"      --border:     rgba(255,255,255,0.09);\n"
	"      --text:       #e8ece9;\n"
	"      --text-2:     #a9b5b1;\n"
	"      --text-mute:  #6f7a76;\n"
	"      --accent:     #2fd0c4;\n"
	"      --accent-soft: rgba(47,208,196,0.14);\n"
	"      --track:      #22302c;\n"
	"      --good:     #1ec91e;\n"
	"      --critical: #e66767;\n"
	"    }\n"
	"  }\n"
	"  :root[data-theme='dark'] {\n"
	"    color-scheme: dark;\n"
	"    --bg:         #0a0f0e;\n"
	"    --surface:    #121917;\n"
	"    --surface-2:  #16201d;\n"
	"    --border:     rgba(255,255,255,0.09);\n"
	"    --text:       #e8ece9;\n"
	"    --text-2:     #a9b5b1;\n"
	"    --text-mute:  #6f7a76;\n"
	"    --accent:     #2fd0c4;\n"
	"    --accent-soft: rgba(47,208,196,0.14);\n"
	"    --track:      #22302c;\n"
	"    --good:     #1ec91e;\n"
	"    --critical: #e66767;\n"
	"  }\n"
	"\n"
	"  * { box-sizing: border-box; }\n"
	"  body {\n"
	"    margin: 0;\n"
	"    background: var(--bg);\n"
	"    color: var(--text);\n"
	"    font-family: var(--font-ui);\n"
	"    padding: clamp(16px, 4vw, 40px);\n"
	"  }\n"
	"  .wrap { max-width: 980px; margin: 0 auto; display: flex; flex-direction: column; gap: 18px; }\n"
	"\n"
	"  .head { display: flex; align-items: baseline; justify-content: space-between; gap: 16px; flex-wrap: wrap; }\n"
	"  .head-id { display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap; }\n"
	"  .head-id .dot {\n"
	"    width: 9px; height: 9px; border-radius: 50%; background: var(--accent);\n"
	"    display: inline-block; align-self: center; box-shadow: 0 0 0 4px var(--accent-soft);\n"
	"  }\n"
	"  h1 { font-size: 20px; font-weight: 600; margin: 0; letter-spacing: -0.01em; }\n"
	"  .head-meta { font-family: var(--font-mono); font-size: 12.5px; color: var(--text-mute); display: flex; gap: 14px; flex-wrap: wrap; }\n"
	"  .head-meta b { color: var(--text-2); font-weight: 500; }\n"
	"\n"
	"  .pills { display: flex; gap: 10px; flex-wrap: wrap; }\n"
	"  .pill { display: flex; align-items: center; gap: 8px; background: var(--surface); border: 1px solid var(--border); border-radius: 999px; padding: 8px 14px 8px 10px; }\n"
	"  .pill .led { width: 8px; height: 8px; border-radius: 50%; flex: none; background: var(--text-mute); }\n"
	"  .pill .led.good { background: var(--good); box-shadow: 0 0 8px color-mix(in srgb, var(--good) 70%, transparent); }\n"
	"  .pill .led.critical { background: var(--critical); box-shadow: 0 0 8px color-mix(in srgb, var(--critical) 70%, transparent); }\n"
	"  .pill .led.active { background: var(--accent); box-shadow: 0 0 8px color-mix(in srgb, var(--accent) 70%, transparent); }\n"
	"  .pill .lbl { font-size: 12px; color: var(--text-mute); }\n"
	"  .pill .val { font-size: 13px; font-weight: 600; }\n"
	"  .pill .val.c-good { color: var(--good); }\n"
	"  .pill .val.c-critical { color: var(--critical); }\n"
	"  .pill .val.c-active { color: var(--accent); }\n"
	"\n"
	"  .card { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 18px 20px; }\n"
	"  .card-title { font-size: 11px; font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase; color: var(--text-mute); margin: 0 0 14px; }\n"
	"\n"
	"  .row-2 { display: grid; grid-template-columns: 1fr 1.4fr; gap: 14px; }\n"
	"  @media (max-width: 640px) { .row-2 { grid-template-columns: 1fr; } }\n"
	"\n"
	"  .hero-value { font-family: var(--font-mono); font-weight: 600; font-size: 40px; line-height: 1; letter-spacing: -0.01em; }\n"
	"  .hero-sub { font-family: var(--font-mono); font-size: 12px; color: var(--text-mute); margin-top: 8px; }\n"
	"\n"
	"  .meter-track { height: 10px; border-radius: 999px; background: var(--track); overflow: hidden; margin-top: 10px; }\n"
	"  .meter-fill { height: 100%; border-radius: 999px; background: var(--accent); transition: width 0.6s ease; }\n"
	"  .meter-labels { display: flex; justify-content: space-between; margin-top: 8px; font-family: var(--font-mono); font-size: 12px; color: var(--text-mute); }\n"
	"  .meter-labels b { color: var(--text); font-weight: 600; }\n"
	"\n"
	"  .tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 10px; }\n"
	"  .tile { background: var(--surface-2); border: 1px solid var(--border); border-radius: 10px; padding: 12px 14px; }\n"
	"  .tile .lbl { font-size: 11.5px; color: var(--text-mute); }\n"
	"  .tile .val { font-family: var(--font-mono); font-size: 20px; font-weight: 600; margin-top: 4px; }\n"
	"  .tile.warn .val { color: var(--critical); }\n"
	"\n"
	"  .controls { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }\n"
	"  .controls input {\n"
	"    font-family: var(--font-mono); font-size: 13px; color: var(--text);\n"
	"    background: var(--surface-2); border: 1px solid var(--border); border-radius: 8px;\n"
	"    padding: 8px 10px; width: 110px;\n"
	"  }\n"
	"  .controls label { font-size: 12px; color: var(--text-mute); display: flex; flex-direction: column; gap: 4px; }\n"
	"  .btn {\n"
	"    font-family: var(--font-ui); font-size: 13px; font-weight: 600; color: white;\n"
	"    background: var(--accent); border: none; border-radius: 999px; padding: 10px 20px;\n"
	"    cursor: pointer;\n"
	"  }\n"
	"  .btn:disabled { opacity: 0.45; cursor: default; }\n"
	"  .btn-danger { background: var(--critical); }\n"
	"\n"
	"  details.tableview { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 4px 20px; }\n"
	"  details.tableview summary { cursor: pointer; padding: 14px 0; font-size: 11px; font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase; color: var(--text-mute); list-style: none; display: flex; align-items: center; gap: 6px; }\n"
	"  details.tableview summary::-webkit-details-marker { display: none; }\n"
	"  details.tableview summary::before { content: '\\25B8'; font-size: 10px; }\n"
	"  details.tableview[open] summary::before { content: '\\25BE'; }\n"
	"  .tablewrap { overflow-x: auto; padding-bottom: 16px; }\n"
	"  table { border-collapse: collapse; width: 100%; font-family: var(--font-mono); font-size: 12.5px; }\n"
	"  th { padding: 6px 10px 6px 0; border-bottom: 1px solid var(--border); text-align: left; font-size: 10.5px; letter-spacing: 0.04em; text-transform: uppercase; color: var(--text-mute); white-space: nowrap; }\n"
	"  td { padding: 6px 10px 6px 0; border-bottom: 1px solid var(--border); white-space: nowrap; }\n"
	"  td:first-child { color: var(--text-mute); }\n"
	"  .segtable td:first-child { color: var(--text); }\n"
	"  .segtable td:last-child { color: var(--text); }\n"
	"  td:last-child:not(.segtable td) { color: var(--text); font-variant-numeric: tabular-nums; text-align: right; }\n"
	"\n"
	"  a.raw-link { color: var(--text-mute); font-family: var(--font-mono); font-size: 12px; text-decoration: none; border-bottom: 1px dotted var(--text-mute); }\n"
	"  a.raw-link:hover { color: var(--accent); border-color: var(--accent); }\n"
	"  a.raw-link-danger { color: var(--text-mute); font-family: var(--font-mono); font-size: 12px; text-decoration: none; border-bottom: 1px dotted var(--text-mute); cursor: pointer; }\n"
	"  a.raw-link-danger:hover { color: var(--critical); border-color: var(--critical); }\n"
	"  .offline { color: var(--critical); font-family: var(--font-mono); font-size: 12.5px; }\n"
	"  .empty-note { color: var(--text-mute); font-family: var(--font-mono); font-size: 12.5px; padding: 10px 0; }\n"
	"\n"
	"  @media (prefers-reduced-motion: reduce) { .meter-fill { transition: none; } }\n"
	"</style>\n"
	"\n"
	"<div class='wrap'>\n"
	"\n"
	"  <div class='head'>\n"
	"    <div class='head-id'>\n"
	"      <span class='dot' id='hdot'></span>\n"
	"      <h1>chrontabulator</h1>\n"
	"      <span class='head-meta' id='hmode'>&mdash;</span>\n"
	"    </div>\n"
	"    <div class='head-meta' id='hstatus'>connecting&hellip;</div>\n"
	"  </div>\n"
	"\n"
	"  <div class='pills'>\n"
	"    <div class='pill'>\n"
	"      <span class='led' id='link-led'></span>\n"
	"      <span class='lbl'>link</span>\n"
	"      <span class='val' id='link-val'>&mdash;</span>\n"
	"    </div>\n"
	"    <div class='pill'>\n"
	"      <span class='led' id='rec-led'></span>\n"
	"      <span class='lbl'>recording</span>\n"
	"      <span class='val' id='rec-val'>&mdash;</span>\n"
	"    </div>\n"
	"  </div>\n"
	"\n"
	"  <div class='row-2'>\n"
	"    <div class='card'>\n"
	"      <p class='card-title'>Records this session</p>\n"
	"      <div class='hero-value' id='hero-total'>&mdash;</div>\n"
	"      <div class='hero-sub' id='hero-sub'>&nbsp;</div>\n"
	"    </div>\n"
	"    <div class='card'>\n"
	"      <p class='card-title'>Link speed</p>\n"
	"      <div class='meter-labels'><span>0</span><b id='speed-label'>&mdash;</b><span>10G</span></div>\n"
	"      <div class='meter-track'><div class='meter-fill' id='speed-fill' style='width:0%'></div></div>\n"
	"    </div>\n"
	"  </div>\n"
	"\n"
	"  <div class='card'>\n"
	"    <p class='card-title'>Recording control</p>\n"
	"    <div class='controls'>\n"
	"      <label>UDP port<input type='number' id='in-port' placeholder='(daemon default)'></label>\n"
	"      <label>Count limit<input type='number' id='in-count' placeholder='0 = unlimited'></label>\n"
	"      <button class='btn' id='btn-start'>Start recording</button>\n"
	"      <button class='btn btn-danger' id='btn-stop' disabled>Stop recording</button>\n"
	"    </div>\n"
	"  </div>\n"
	"\n"
	"  <div class='card'>\n"
	"    <p class='card-title'>NVMe / storage</p>\n"
	"    <div class='tiles' id='nvme-tiles'></div>\n"
	"  </div>\n"
	"\n"
	"  <div class='card'>\n"
	"    <div style='display:flex;justify-content:space-between;align-items:baseline;margin-bottom:14px'>\n"
	"      <p class='card-title' style='margin:0'>Segments</p>\n"
	"      <label style='font-size:12px;color:var(--text-mute);display:flex;align-items:center;gap:6px'>\n"
	"        <input type='checkbox' id='in-show-deleted'> show deleted\n"
	"      </label>\n"
	"    </div>\n"
	"    <div class='tablewrap'><table class='segtable' id='segtable'></table></div>\n"
	"    <div class='empty-note' id='seg-empty' style='display:none'>No segments recorded yet.</div>\n"
	"  </div>\n"
	"\n"
	"  <details class='tableview'>\n"
	"    <summary>Raw status</summary>\n"
	"    <div class='tablewrap'><table id='rawtable'></table></div>\n"
	"    <p><a class='raw-link' href='/status.json' target='_blank'>/status.json</a></p>\n"
	"  </details>\n"
	"\n"
	"</div>\n"
	"\n"
	"<script>\n"
	"(function () {\n"
	"  'use strict';\n"
	"\n"
	"  function fmt(n) { return Number(n).toLocaleString('en-US'); }\n"
	"\n"
	"  function fmtUptime(sec) {\n"
	"    sec = Math.floor(sec);\n"
	"    var h = Math.floor(sec / 3600), m = Math.floor((sec % 3600) / 60), s = sec % 60;\n"
	"    if (h > 0) return h + 'h ' + m + 'm';\n"
	"    return m + 'm ' + s + 's';\n"
	"  }\n"
	"\n"
	"  function fmtBytes(n) {\n"
	"    if (n < 1e3) return n + ' B';\n"
	"    if (n < 1e6) return (n / 1e3).toFixed(1) + ' KB';\n"
	"    if (n < 1e9) return (n / 1e6).toFixed(1) + ' MB';\n"
	"    return (n / 1e9).toFixed(2) + ' GB';\n"
	"  }\n"
	"\n"
	"  function setPill(ledId, valId, ok, textOk, textBad, activeClass) {\n"
	"    var led = document.getElementById(ledId), val = document.getElementById(valId);\n"
	"    var cls = activeClass || 'good';\n"
	"    led.className = 'led ' + (ok ? cls : 'critical');\n"
	"    val.className = 'val ' + (ok ? 'c-' + cls : 'c-critical');\n"
	"    val.textContent = ok ? textOk : textBad;\n"
	"  }\n"
	"\n"
	"  function row(label, value) { return '<tr><td>' + label + '</td><td>' + value + '</td></tr>'; }\n"
	"\n"
	"  function tile(id, label, warn) {\n"
	"    return '<div class=\"tile' + (warn ? ' warn' : '') + '\"><div class=\"lbl\">' + label +\n"
	"           '</div><div class=\"val\" id=\"' + id + '\">&mdash;</div></div>';\n"
	"  }\n"
	"\n"
	"  document.getElementById('nvme-tiles').innerHTML =\n"
	"    tile('t-block', 'Block size') + tile('t-total', 'Capacity') +\n"
	"    tile('t-used', 'Data used') + tile('t-free', 'Data free') +\n"
	"    tile('t-toc', 'TOC used') + tile('t-written', 'Bytes written') +\n"
	"    tile('t-writes', 'Writes completed') + tile('t-werr', 'Write errors', true);\n"
	"\n"
	"  var recording = false;\n"
	"\n"
	"  function update(d) {\n"
	"    document.getElementById('hstatus').textContent = 'live';\n"
	"    document.getElementById('hmode').innerHTML = 'port <b>' + (d.udp_port || '\\u2014') +\n"
	"      '</b> \\u00B7 uptime <b>' + fmtUptime(d.uptime_sec) + '</b>';\n"
	"\n"
	"    setPill('link-led', 'link-val', d.link_up,\n"
	"      'up \\u00B7 ' + (d.link_speed_mbps / 1000).toFixed(1).replace('.0', '') + 'G full-duplex',\n"
	"      'down', 'good');\n"
	"    setPill('rec-led', 'rec-val', d.recording,\n"
	"      'segment ' + d.current_segment_id, 'idle', 'active');\n"
	"\n"
	"    recording = !!d.recording;\n"
	"    document.getElementById('btn-start').disabled = recording;\n"
	"    document.getElementById('btn-stop').disabled = !recording;\n"
	"\n"
	"    document.getElementById('hero-total').textContent = fmt(d.current_segment_record_count);\n"
	"    document.getElementById('hero-sub').textContent = recording\n"
	"      ? (fmt(d.current_segment_dropped_count) + ' dropped \\u00B7 ' + d.current_segment_elapsed_sec.toFixed(1) + 's elapsed')\n"
	"      : 'not recording';\n"
	"\n"
	"    document.getElementById('speed-label').textContent = d.link_up ? fmt(d.link_speed_mbps) + ' Mbps' : 'no link';\n"
	"    document.getElementById('speed-fill').style.width = Math.min(100, (d.link_speed_mbps / 10000) * 100) + '%';\n"
	"\n"
	"    document.getElementById('t-block').textContent = fmt(d.block_size) + ' B';\n"
	"    document.getElementById('t-total').textContent = fmtBytes(d.total_bytes);\n"
	"    document.getElementById('t-used').textContent = fmtBytes(d.data_used_bytes);\n"
	"    document.getElementById('t-free').textContent = fmtBytes(d.data_free_bytes);\n"
	"    document.getElementById('t-toc').textContent = d.segments_used + '/' + d.toc_slot_count +\n"
	"      ' (' + d.toc_capacity_pct.toFixed(1) + '%)';\n"
	"    document.getElementById('t-written').textContent = fmtBytes(d.bytes_written_total);\n"
	"    document.getElementById('t-writes').textContent = fmt(d.writes_completed_total);\n"
	"    document.getElementById('t-werr').textContent = fmt(d.write_errors_total);\n"
	"\n"
	"    var rows = [\n"
	"      row('mode', d.mode), row('uptime_sec', d.uptime_sec),\n"
	"      row('recording', d.recording), row('current_segment_id', d.current_segment_id),\n"
	"      row('current_segment_record_count', d.current_segment_record_count),\n"
	"      row('current_segment_dropped_count', d.current_segment_dropped_count),\n"
	"      row('udp_port', d.udp_port),\n"
	"      row('link_up', d.link_up), row('link_speed_mbps', d.link_speed_mbps),\n"
	"      row('have_hw_stats', d.have_hw_stats), row('hw_ipackets', d.hw_ipackets),\n"
	"      row('hw_ibytes', d.hw_ibytes), row('hw_imissed', d.hw_imissed), row('hw_ierrors', d.hw_ierrors),\n"
	"      row('bdev_name', d.bdev_name), row('block_size', d.block_size),\n"
	"      row('total_bytes', d.total_bytes),\n"
	"      row('toc_slot_count', d.toc_slot_count), row('segments_used', d.segments_used),\n"
	"      row('data_used_bytes', d.data_used_bytes), row('data_free_bytes', d.data_free_bytes),\n"
	"      row('bytes_written_total', d.bytes_written_total),\n"
	"      row('writes_completed_total', d.writes_completed_total),\n"
	"      row('write_errors_total', d.write_errors_total),\n"
	"    ];\n"
	"    document.getElementById('rawtable').innerHTML = rows.join('');\n"
	"  }\n"
	"\n"
	"  function poll() {\n"
	"    fetch('/status.json', { cache: 'no-store' })\n"
	"      .then(function (r) { return r.json(); })\n"
	"      .then(update)\n"
	"      .catch(function () {\n"
	"        document.getElementById('hstatus').innerHTML = '<span class=\"offline\">connection lost</span>';\n"
	"      });\n"
	"  }\n"
	"\n"
	"  function segRow(s) {\n"
	"    var actions = '<a class=\"raw-link\" href=\"/segments/' + s.segment_id +\n"
	"      '/records.json\" target=\"_blank\">view</a> &middot; ' +\n"
	"      '<a class=\"raw-link-danger\" data-del=\"' + s.segment_id + '\">delete</a>';\n"
	"    if (s.state === 'open') {\n"
	"      return '<tr><td>' + s.segment_id + '</td><td>open</td><td colspan=\"4\">in progress / never finalized</td><td>' +\n"
	"        actions + '</td></tr>';\n"
	"    }\n"
	"    return '<tr><td>' + s.segment_id + '</td><td>' + s.state + '</td><td>' + s.wall_clock_start +\n"
	"      '</td><td>' + s.duration_sec.toFixed(1) + 's</td><td>' + fmt(s.record_count) +\n"
	"      '</td><td>' + fmt(s.dropped_count) + '</td><td>' + actions + '</td></tr>';\n"
	"  }\n"
	"\n"
	"  function loadSegments() {\n"
	"    var includeDeleted = document.getElementById('in-show-deleted').checked;\n"
	"    fetch('/segments.json' + (includeDeleted ? '?include_deleted=1' : ''), { cache: 'no-store' })\n"
	"      .then(function (r) { return r.json(); })\n"
	"      .then(function (d) {\n"
	"        var empty = document.getElementById('seg-empty');\n"
	"        var table = document.getElementById('segtable');\n"
	"        if (!d.segments || d.segments.length === 0) {\n"
	"          table.innerHTML = '';\n"
	"          empty.style.display = 'block';\n"
	"          return;\n"
	"        }\n"
	"        empty.style.display = 'none';\n"
	"        table.innerHTML = '<thead><tr><th>id</th><th>state</th><th>start</th>' +\n"
	"          '<th>duration</th><th>records</th><th>dropped</th><th>actions</th></tr></thead><tbody>' +\n"
	"          d.segments.map(segRow).join('') + '</tbody>';\n"
	"        table.querySelectorAll('[data-del]').forEach(function (a) {\n"
	"          a.addEventListener('click', function () {\n"
	"            if (!confirm('Delete segment ' + a.getAttribute('data-del') + '? Its space will not be freed.')) return;\n"
	"            fetch('/segments/' + a.getAttribute('data-del') + '/delete', { method: 'POST' })\n"
	"              .then(loadSegments);\n"
	"          });\n"
	"        });\n"
	"      });\n"
	"  }\n"
	"\n"
	"  document.getElementById('btn-start').addEventListener('click', function () {\n"
	"    var port = document.getElementById('in-port').value;\n"
	"    var count = document.getElementById('in-count').value;\n"
	"    var qs = [];\n"
	"    if (port) qs.push('port=' + encodeURIComponent(port));\n"
	"    if (count) qs.push('count_limit=' + encodeURIComponent(count));\n"
	"    fetch('/recording/start' + (qs.length ? '?' + qs.join('&') : ''), { method: 'POST' })\n"
	"      .then(function () { setTimeout(loadSegments, 300); });\n"
	"  });\n"
	"  document.getElementById('btn-stop').addEventListener('click', function () {\n"
	"    fetch('/recording/stop', { method: 'POST' }).then(function () { setTimeout(loadSegments, 300); });\n"
	"  });\n"
	"  document.getElementById('in-show-deleted').addEventListener('change', loadSegments);\n"
	"\n"
	"  poll();\n"
	"  setInterval(poll, 1000);\n"
	"  loadSegments();\n"
	"})();\n"
	"</script>\n"
	"\n";

#endif
